#!/bin/sh

# ### BEGIN INIT INFO
# Provides: watchdog
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Building supervision with Raspberry Pi
# Description:
### END INIT INFO

DAEMON=/usr/bin/python
ARGS="-m watchdog"
PIDFILE=/var/run/watchdog.pid

test -x $DAEMON || exit 0

case "$1" in

    start)
    
    echo "Starting watchdog"
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $ARGS
    ;;

    stop)
    echo "Shutting down watchdog"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm $PIDFILE
    ;;

    restart)
    echo "Restarting watchdog"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm $PIDFILE
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $ARGS
    ;;

    status)
    if [ -f $PIDFILE ]; then
		echo '***********************'
		echo '* watchdog is running *'
		echo '***********************'
	else
		echo '***************************'
		echo '* watchdog is NOT running *'
		echo '***************************'
	fi
    ;;

    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac
exit 0
