#!/bin/bash

# Custom install script for the WATCHDOG capture plugin

# determine plugin directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CWD=$(pwd)

# download image gallery jQuery library
cd /usr/share/javascript
git clone git://github.com/sachinchoolur/lightGallery
cd lightGallery
git checkout tags/1.3.5

# restore working directory 
cd $CWD
